//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT7_SkalochkinFedor_ISP_321_MasterFloor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsImport
    {
        public int IDProducts { get; set; }
        public int ProductsType { get; set; }
        public int TitleProducts { get; set; }
        public long Article { get; set; }
        public double MinPrice { get; set; }
    
        public virtual ProductTypeImport ProductTypeImport { get; set; }
        public virtual TitleProducts TitleProducts1 { get; set; }
    }
}
